import { Product, RawMaterial, User, SystemSettings } from '../types';

export const rawMaterials: RawMaterial[] = [
  {
    id: 'mat-1',
    name: 'صوص',
    unit: 'g',
    unitCost: 0.5,
    currentStock: 500,
    minStock: 200,
    targetStock: 1000,
    category: 'مكونات',
  },
  {
    id: 'mat-2',
    name: 'كوب',
    unit: 'piece',
    unitCost: 2,
    currentStock: 50,
    minStock: 30,
    targetStock: 100,
    category: 'مستلزمات',
  },
  {
    id: 'mat-3',
    name: 'سيفن',
    unit: 'ml',
    unitCost: 0.05,
    currentStock: 3000,
    minStock: 1000,
    targetStock: 5000,
    category: 'مشروبات',
  },
  {
    id: 'mat-4',
    name: 'ثلج',
    unit: 'g',
    unitCost: 0.02,
    currentStock: 2000,
    minStock: 500,
    targetStock: 3000,
    category: 'مكونات',
  },
  {
    id: 'mat-5',
    name: 'شفاطة',
    unit: 'piece',
    unitCost: 0.5,
    currentStock: 80,
    minStock: 40,
    targetStock: 150,
    category: 'مستلزمات',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'صودا',
    sku: 'SODA-001',
    barcode: '1234567890123',
    cost: 40,
    price: 80,
    profit: 40,
    category: 'مشروبات',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1676300182703-33124fbacbcf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzb2RhJTIwZHJpbmslMjBnbGFzc3xlbnwxfHx8fDE3NjQ1OTg3MjJ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    recipe: [
      {
        materialId: 'mat-1',
        materialName: 'صوص',
        quantity: 20,
        unit: 'g',
        unitCost: 0.5,
        totalCost: 10,
      },
      {
        materialId: 'mat-2',
        materialName: 'كوب',
        quantity: 1,
        unit: 'piece',
        unitCost: 2,
        totalCost: 2,
      },
      {
        materialId: 'mat-3',
        materialName: 'سيفن',
        quantity: 200,
        unit: 'ml',
        unitCost: 0.05,
        totalCost: 10,
      },
      {
        materialId: 'mat-4',
        materialName: 'ثلج',
        quantity: 100,
        unit: 'g',
        unitCost: 0.02,
        totalCost: 2,
      },
      {
        materialId: 'mat-5',
        materialName: 'شفاطة',
        quantity: 1,
        unit: 'piece',
        unitCost: 0.5,
        totalCost: 0.5,
      },
    ],
  },
  {
    id: 'prod-2',
    name: 'عصير برتقال',
    sku: 'JUICE-001',
    cost: 35,
    price: 70,
    profit: 35,
    category: 'عصائر',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1641659735894-45046caad624?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvcmFuZ2UlMjBqdWljZSUyMGdsYXNzfGVufDF8fHx8MTc2NDQ4NDA2Mnww&ixlib=rb-4.1.0&q=80&w=1080',
    recipe: [
      {
        materialId: 'mat-2',
        materialName: 'كوب',
        quantity: 1,
        unit: 'piece',
        unitCost: 2,
        totalCost: 2,
      },
      {
        materialId: 'mat-4',
        materialName: 'ثلج',
        quantity: 80,
        unit: 'g',
        unitCost: 0.02,
        totalCost: 1.6,
      },
      {
        materialId: 'mat-5',
        materialName: 'شفاطة',
        quantity: 1,
        unit: 'piece',
        unitCost: 0.5,
        totalCost: 0.5,
      },
    ],
  },
  {
    id: 'prod-3',
    name: 'قهوة',
    sku: 'COFFEE-001',
    cost: 25,
    price: 55,
    profit: 30,
    category: 'مشروبات ساخنة',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1631305588911-a223ec83ddbc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2ZmZWUlMjBjdXAlMjBob3R8ZW58MXx8fHwxNzY0NTE0ODM3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    recipe: [
      {
        materialId: 'mat-2',
        materialName: 'كوب',
        quantity: 1,
        unit: 'piece',
        unitCost: 2,
        totalCost: 2,
      },
    ],
  },
  {
    id: 'prod-4',
    name: 'سموثي فواكه',
    sku: 'SMOOTHIE-001',
    cost: 45,
    price: 90,
    profit: 45,
    category: 'عصائر طبيعية',
    isActive: true,
    imageUrl: 'https://images.unsplash.com/photo-1655992590262-aeadeef445b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbW9vdGhpZSUyMGZydWl0JTIwZHJpbmt8ZW58MXx8fHwxNzY0NTk4OTA0fDA&ixlib=rb-4.1.0&q=80&w=1080',
    recipe: [
      {
        materialId: 'mat-2',
        materialName: 'كوب',
        quantity: 1,
        unit: 'piece',
        unitCost: 2,
        totalCost: 2,
      },
      {
        materialId: 'mat-4',
        materialName: 'ثلج',
        quantity: 150,
        unit: 'g',
        unitCost: 0.02,
        totalCost: 3,
      },
      {
        materialId: 'mat-5',
        materialName: 'شفاطة',
        quantity: 1,
        unit: 'piece',
        unitCost: 0.5,
        totalCost: 0.5,
      },
    ],
  },
];

export const users: User[] = [
  {
    id: 'user-1',
    username: 'owner',
    password: '123456',
    role: 'owner',
    fullName: 'أحمد المالك',
    isActive: true,
    createdAt: new Date('2025-01-01'),
    salary: 5000,
  },
  {
    id: 'user-2',
    username: 'cashier',
    password: '123456',
    role: 'cashier',
    fullName: 'محمد الكاشير',
    isActive: true,
    createdAt: new Date('2025-01-05'),
    salary: 3000,
  },
  {
    id: 'user-3',
    username: 'cashier2',
    password: '123456',
    role: 'cashier',
    fullName: 'خالد الموظف',
    isActive: true,
    createdAt: new Date('2025-01-10'),
    salary: 3000,
  },
];

export const defaultSettings: SystemSettings = {
  storeName: 'متجر المشروبات',
  receiptMessage: 'شكراً لزيارتكم - نتمنى لكم يوماً سعيداً',
  taxRate: 0,
  currency: 'ج.م',
  workStartTime: '09:00',
  workEndTime: '18:00',
  lateThreshold: 15,
};